### ISSUE TITLE
Points at wrong plugin

### ISSUE THREAD

**Issue by Nocturnal42** [StarBound6494/NewGods#4]
Might want to change the references to https://www.spigotmc.org/resources/new-gods.55163/ to your actual page.

**Comment by StarBound6494** [comment]
I unfortunantly do not have access to that page. 
The current version of the plugin is being updated here: https://www.spigotmc.org/resources/new-new-gods.89188/

**Comment by Nocturnal42** [comment]
Which is exactly my point. You have two instances of the incorrect url in your codebase, one of which is linked to the plugin command, informing players in game of the wrong url for the plugin. 

```
src/main/java/com/fluff_stuff/newgods/commands/Plugin.java
config.yml

```

Both need to be updated to your actual page.\

**Comment by StarBound6494** [comment]
Ah. I did not understand what you meant. I will resolve that next update
